"""empty message

Revision ID: 309415622055
Revises: 1273b73b850b
Create Date: 2022-06-05 18:19:44.181727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309415622055'
down_revision = '1273b73b850b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
