"""empty message

Revision ID: 925ed82dfc5b
Revises: 18274035da5c
Create Date: 2022-06-06 18:47:54.676780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925ed82dfc5b'
down_revision = '18274035da5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Venue', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
